spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: info@chirp.jja-systems.site
  datasource:
    url: jdbc:postgresql://db.cnewocdpgxqrtfxvytyu.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}

jwt:
  expiration-minutes: 15

nginx:
  required-proxy: true

chirp:
  email:
    url: "https://chirp.jja-systems.site"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins: "https://chirp.jja-systems.site"
  amqp:
    queue-prefix: prod