spring:
  application:
    name: chirp

  data:
    redis:
      host: "redis-13833.c308.sa-east-1-1.ec2.redns.redis-cloud.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 13833
      connect-timeout: 5000ms
      timeout: 2000ms
  datasource:
    username: postgres.cnewocdpgxqrtfxvytyu
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5
        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  mail:
    port: 587
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: jaragua.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: erzatygl
    ssl:
      enabled: true
    virtual-host: erzatygl
    listener:
      simple:
        acknowledge-mode: AUTO
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}

chirp:
  email:
    from: mail@jja-systems.com
    verification:
      expiry-hours: 24

    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://cnewocdpgxqrtfxvytyu.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

firebase:
  credentials_path: "classpath:firebase-credentials/chirp-firebase-admin-sdk.json"