spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: jjasystems@sandbox1c110898d725454485ab5df26f24f4cb.mailgun.org
  datasource:
    url: jdbc:postgresql://db.cnewocdpgxqrtfxvytyu.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}

jwt:
  expiration-minutes: 15

nginx:
  required-proxy: true

chirp:
  email:
    url: "https://chirp.jja-systems.site"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins: "https://chirp.jja-systems.site"